### ISSUE TITLE
negative charge density

### ISSUE THREAD

**Issue by Masoudrahbar** [aoterodelaroza/critic2#10]
I am calculating the bonding properties of NiMn alloy in bulk and slab structures. in the bulk structure all the charge densities are positive at critical points but in the slab structure some of them (actually most of them) get negative. can somebody please explain this?

**Comment by aoterodelaroza** [comment]
Hi @masoudrahbar, 

The densities from a cube file in interstitial or vacuum regions can
become slightly negative because of numerical noise either from the
electronic structure program or from critic2's interpolation. For more
specifics, can you please provide your density, structure, and input
files?

* Masoudrahbar <notifications@github.com> [2018-01-19 17:24:46 +0000]:

**Comment by Masoudrahbar** [comment]
thank you for the response yes just the regions near the vacuum shows negative values. I have another question and that is about the laplacian. in the bulk all of them are positive but in the slab most of them are negative is this normal?I attached the input files
[attachments.zip](https://github.com/aoterodelaroza/critic2/files/1647450/attachments.zip)

**Comment by aoterodelaroza** [comment]
Yep, it's clearly noise. If you try:

   crystal zero-case.cube
   load cube zero-case.cube
   auto
   cpreport bleh.cml

and then view the resulting cml with avogadro (you need to set up
openbabel's element.txt, as described in the manual), you will see
that the vacuum is packed with spurious CPs. The easiest way to get
rid of them is to use the DISCARD keyword to prune those that have
density less than a very small value:

   crystal zero-case.cube
   load cube zero-case.cube
   auto discard "$1 < 1e-3"
   cpreport bleh.cml

With this you get:

   * Critical point list, final report (non-equivalent cps)
     Topological class (n|b|r|c): 6(10) 33(62) 37(74) 11(21) 
     Morse sum: 1

and the vacuum CPs are gone. As for the Laplacian, the same comment
applies. The Laplacian is even more noisy than the density in regions
of low density. 

* Masoudrahbar <notifications@github.com> [2018-01-19 17:48:21 +0000]:

**Comment by Masoudrahbar** [comment]
I really appreciate. solved

**Comment by Masoudrahbar** [comment]
I really appreciate. solved
