### ISSUE TITLE
compiling with gfortran-6.4: warning

### ISSUE THREAD

**Issue by Ceasea** [aoterodelaroza/critic2#11]
hello
I try to compile critic2_stable. Version of gcc is 6.4.0 20171010 (Ubuntu 6.4.0-8ubuntu1)

during the process of _make_, some warnings appear.  Two warnings are listed here , while the rest are similar like these ( if necessary, I can paste all of them ):

_Warning: Type mismatch in argument ‘ch’ at (1); passed COMPLEX(8) to REAL(8)
cfftnd.f90:599:72:                                                                                                          
       call cmf4kf ( lot, ido, l1, na, c, jump, inc, ch, 1, lot, wa(iw) )
                                                                        1
Warning: Type mismatch in argument ‘cc’ at (1); passed COMPLEX(8) to REAL(8)
cfftnd.f90:601:72:
       call cmf4kf ( lot, ido, l1, na, ch, 1, lot, c, jump, inc, wa(iw) )_

after the command of make and make install without any errors, critic2 runs normally and I try one of the examples, using files provided:
_table3.cri, covellite.AECCAR0, covellite.AECCAR2 and covellite.CHGCAR_

the result shows four ring critical points:
![_my](https://user-images.githubusercontent.com/27671499/36631681-748d0020-19b7-11e8-9677-ef81569638c3.PNG)

while the original document _Journal of physical chemistry A 118 5823 garcia First-Principles Calculations and Electron Density Topological Analysis of Covellite (CuS)_ gives three ring critical points.
![Uploading 捕获.PNG…]()

so, I was wondering whether there was any connection between the  warning messages and error of the number of ring critical points.
thanks.

**Comment by aoterodelaroza** [comment]
Hi @Ceasea,

Those warnings are from the FFT library, and they are normal during compilation. Plus, that part of the code is not used to calculate the critical points. Finding critical points in densities given on a grid can be tricky. Precisely the covellite example is discussed in issue #7 . I'll take a look in the near future and write some suitable explanations in that example.

**Comment by Ceasea** [comment]
Oh ,I see. 
In #7, I found that the positions of two bond critical points are nearly the same, so that we can consider they are one point in fact.

The positions of ring critical points in my case are different from each other, but the positions of _r4_ and _c3_ are the same, which means they are the same one.

well, thanks a lot for your time.

**Comment by Ceasea** [comment]
by the way, I got nearly the same bond critical points( positions and charge density at the points),  there is a numerical misfit of Laplacian of charge density.
In my result, the Laplacian of charge density at bont critical points are about 0.156,  0.202, 0.185, -0.080,
while, the Laplacians of charge density at bond criticial points  in the paper are 0.102, 0.103, 0.098, -0.0923.

Considering the fact that we just need to identify the symbol(+,-) of  Laplacian of charge density at a bond critcial point, the numerical misfit could be ignored?

**Comment by aoterodelaroza** [comment]
Probably. Are you using doing exactly the same calculations as they
did in the paper (functional, geometry, cutoffs, number of points in
the grid, etc.)?

* Ceasea <notifications@github.com> [2018-02-25 03:28:33 +0000]:

**Comment by Ceasea** [comment]
I use the input files from http://schooner.chem.dal.ca/downloads/critic2/critic2_examples_data.tar.xz

**Comment by aoterodelaroza** [comment]
Ah. Then those differences are perfectly normal. I didn't pay any
attention to reproducing exactly the same calculation conditions as in
the article, so the Laplacian values should be in the ballpark, but
not more than that.

* Ceasea <notifications@github.com> [2018-02-25 06:25:44 +0000]:

**Comment by Ceasea** [comment]
okay, got it.
thanks a lot.
