### ISSUE TITLE
why I can't obtain *.obj and *.xyz documents?

### ISSUE THREAD

**Issue by lorna639** [aoterodelaroza/critic2#14]
I want to obtain the BCP of a material. and in the input 
"cpreport obj cell border
write mol.xyz
cpreport short"
but in the output, there is no *.obj and *.xyz docuements.
in the end of the output,  
"* WRITE obj file: obj
ERROR(obj_open): could not parse file name
ERROR(obj_open): could not parse file name" 

I want to obtain your help.
Thank you.

**Comment by aoterodelaroza** [comment]
Hi @lorna639. It should be:

cpreport blah.obj cell border

This will create a file called "blah.obj".

* lorna639 <notifications@github.com> [2018-06-03 01:26:34 -0700]:
> I want to obtain the BCP of a material. and in the input 
> "cpreport obj cell border
> write mol.xyz
> cpreport short"
> but in the output, there is no *.obj and *.xyz docuements.
> in the end of the output,  
> "* WRITE obj file: obj
> ERROR(obj_open): could not parse file name
> ERROR(obj_open): could not parse file name" 
> 
> I want to obtain your help.
> Thank you.
