### ISSUE TITLE
Inconsistent number format in root-grad.cube

### ISSUE THREAD

**Issue by weixie4** [aoterodelaroza/critic2#17]
Hi Aotero, 

Sorry to harass you again by submitting another issue... I found that for very large values of reduced density gradient s (when density rho is very small) from NCI analysis, the format in root-grad.cube is something like 0.17557+106 while common values of s are in the scientific format like 0.12838E+01. The character E is missing in the former and led to problems when I did postprocessing of root-grad.cube using Python. The field width of both are the same so I assume this is some Fortran conversion that drops E to accommodate one more digit for the exponent? Is it possible that we make the output format consistent for all values (keeping E)? For example, use one less digit for the base when the exponent increases from 2 to 3 digits. Thanks.

Best,
Wei

**Comment by aoterodelaroza** [comment]
No worries. I just pushed the change to fix it. Can you please try
again?

**Comment by weixie4** [comment]
The new version worked. Thanks again.
