### ISSUE TITLE
Units of density and Laplacian?

### ISSUE THREAD

**Issue by gooaah** [aoterodelaroza/critic2#20]
I am using critic2 to ananlyze the charge density from VASP. l am confused of the units of density and Laplacin in "Additional properties at the critical points". Unit of density is e/A^3 or e/Bohr^3?

**Comment by aoterodelaroza** [comment]
Always e/bohr^3 (atomic units), regardless of what the units in the
source density are.

* Hao Gao <notifications@github.com> [2019-04-10 19:03:33 -0700]:

**Comment by gooaah** [comment]
@aoterodelaroza Thanks, that is helpful.

**Comment by 528012** [comment]
> 我正在使用 critic2 来分析 VASP 的电荷密度。我对“临界点的附加特性”中的密度和 Laplacin 的单位感到困惑。密度单位是 e/A^3 还是 e/Bohr^3？
Hello, I would like to inquire if there is a tutorial for critic2?

**Comment by aoterodelaroza** [comment]
The documentation for the program is in https://aoterodelaroza.github.io/ and it contains examples. The source also contains an examples/ directory with the examples I have not migrated yet to the website. Please don't use unrelated issues for questions: either send an e-mail or open a new issue.
