### ISSUE TITLE
integrable clear not working

### ISSUE THREAD

**Issue by Ceasea** [aoterodelaroza/critic2#23]
Hi @aoterodelaroza 

integrable clear not working in my situation. I dont know it is a bug or not. I post message about the command and critic2 compiling.

---------------------------------------------------------------------------------

%% integrable 2 LAP
 List of integrable properties (7)
 Id  Type  Field  Name
    1   v        0  Volume
    2  fval      2  Pop
    3  lval      2  Lap
    4   f        2  $2
    5   f        2  $2#f
    6  lap       2  $2#lap
    7  lap       2  $2#lap

integrable clear
%% integrable clear

List of integrable properties (7)
 Id  Type  Field  Name
    1   v        0  Volume
    2  fval      2  Pop
    3  lval      2  Lap
    4   f        2  $2
    5   f        2  $2#f
    6  lap       2  $2#lap
    7  lap       2  $2#lap

---------------------------------------------------------------------------------

compling critic2

---------------------------------------------------------------------------------

critic2 (development), commit (config) no-git
 compile host: Linux ceasea-VirtualBox 4.15.0-43-generic #46-Ubuntu SMP Thu Dec 6 14:44:00 UTC 2018 i686 i686 i686 GNU/Linux
 compile date: 2019年 01月 03日 星期四 14:36:01 CST
    using f77: gfortran -g -O2
          f90: gfortran -g -O2 -ffree-form -ffree-line-length-none -fopenmp
            c: gcc -g -O2 -Iqhull/
      ldflags:
       debug?: no
 compiled dat: /usr/local/share/critic2
      datadir: /usr/local/share/critic2
     dic file: /usr/local/share/critic2/cif/cif_core.dic
...was found?: T

---------------------------------------------------------------------------------

**Comment by aoterodelaroza** [comment]
Hi @ceasea. Sorry for the wait. I've just pushed a fix to the
development branch. Can you please pull, recompile, and try again?

**Comment by Ceasea** [comment]
ok，thanks 汪进凯 邮箱：ceasea@i.shu.edu.cn 签名由 网易邮箱大师 定制 On 05/14/2019 04:34, aoterodelaroza wrote: Hi @ceasea. Sorry for the wait. I've just pushed a fix to the development branch. Can you please pull, recompile, and try again? — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by Ceasea** [comment]
hi @aoterodelaroza 

I download the latest critic2-master package and try to compile but fail in the first step autoreconf.

> configure.ac:11: error: AC_INIT should be called with package and version arguments
/usr/share/aclocal-1.15/init.m4:29: AM_INIT_AUTOMAKE is expanded from...
configure.ac:11: the top level
autom4te: /usr/bin/m4 failed with exit status: 1
aclocal: error: echo failed with exit status: 1
autoreconf: aclocal failed with exit status: 1
>

I have checked the previous version of Critic2-master with autoreconf and ./configure, and verything goes well.
I am not sure what happened.

**Comment by aoterodelaroza** [comment]
That is odd. A fresh clone of the critic2-master works for me, and I
didn't touch the build system in the last fix.

Try "make distclean" first, then autoreconf, etc. If that doesn't
work, try replacing the AC_INIT line in configure.ac with:
~~~
AC_INIT(critic2,1.0)
~~~

**Comment by Ceasea** [comment]
ok, i will try
