### ISSUE TITLE
data incompatible from auto and cube grid

### ISSUE THREAD

**Issue by Ceasea** [aoterodelaroza/critic2#24]
[CHGCAR.zip](https://github.com/aoterodelaroza/critic2/files/3205543/CHGCAR.zip)

Hi @aoterodelaroza 

I conducted two steps to test if the data is self-consistent.
step 1.

> cystal CHGCAR
load CHGCAR
auto
cpreport 
test.cif

In the output, I get the Lap of one BCP ( 0.75 0.25 0.5), which is negative.

step 2.
> crystal CHGCAR
load CHGCAR
cube grid field 1 LAP file bleh.cube

With the file bleh.cube ( the Laplacian of CHGCAR), I use VESTA to get the LAP of that BCP.
this process is 
>open bleh.cube with VESTA
in the toolbar, click "Utilities"  and then “LINE Profile"
input two point coordinations between which that BCP is located
( cooridnations are (0.5,0,0.5) and (1,0.5,0.5), and then that BCP is in the midpoint.)

A file containing the data of the Laplacian along the two coordinations is generated, from which 
I found there is no negative value around the midpoint, or most value are positive around the midpoint.

step 3.
 I use VESTA to generate the Laplacian of CHGCAR, and the data is stored in file CHGCAR.led.
>in the toolbar, click "Utilities" and then "Conversion of Charge density..."

In the same way, I get the line profile of that two point coordinations in CHGCAR.led.
This time, I found there is negative value around the midpoint.

Any ideas about my test are appreciated. CHGCAR is loaded up.
thanks.

**Comment by aoterodelaroza** [comment]
Sure. I would not trust anything AUTO says when it is a applied to a grid. It may give the correct result, but there are unresolved issues with the calculation of derivatives and the interpolation that make the CP search unreliable.

Regarding the Laplacian at a given point: the best way to calculate it from a grid is to first calculate the grid containing the Laplacian with a Fourier transform operation, and then obtain the value of that new grid a the point you want. I suspect this is the same VESTA does. In your example:
`
crystal CHGCAR
load CHGCAR
load as lap 1
point 0.75 0.25 0.5 field 2
`
or whatever point you need. If you want a line, use the LINE command instead. The problem with the way you did it is that the "normal"  way of calculating the Laplacian of a field is by using its three second derivatives and this is more or less broken for grids, for the same reason AUTO is.

**Comment by Ceasea** [comment]
I see. the problem is still caused by grid data.
thanks a lot
