### ISSUE TITLE
Unable to generate configure file and configure file not working

### ISSUE THREAD

**Issue by manaslkht** [aoterodelaroza/critic2#27]
Hello,

I am trying to install critic2 on my macOS (Mojave 10.14.6). I downloaded the .zip file from the github repository and unzipped the folder. On entering the folder, as per the instructions provided on the github page I ran autoreconf. I get the following errors and and the configure file is not created.

configure.ac:11: error: AC_INIT should be called with package and version arguments
/usr/local/Cellar/automake/1.16.1_1/share/aclocal-1.16/init.m4:171: AM_INIT_AUTOMAKE is expanded from...
configure.ac:11: the top level
autom4te: /usr/bin/m4 failed with exit status: 1
aclocal: error: echo failed with exit status: 1
autoreconf: aclocal failed with exit status: 1

Alternatively, I ran autoconf command but I get the following errors,

configure.ac:11: error: possibly undefined macro: AM_INIT_AUTOMAKE
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
configure.ac:46: error: possibly undefined macro: AM_CONDITIONAL

However, the configure file is created. So I tried to execute the file by ./configure command but ended up getting the following error,

configure: error: cannot find sources (critic2) in . or ..

I am not sure if there is a bug in the configure.ac file or if something is missing in my libraries. Can you please help me with this? Please let me know if you need any additional information on this.

Thank you!

**Comment by aoterodelaroza** [comment]
Hi, thanks for the report! That happens because the second argument in
AC_INIT is empty, because the macro grabs the version from git. I'm
moving to cmake so this won't be a problem for much longer. In the
interim, I've pushed a change to configure.ac to fix this. You can do
it on your copy simply by replacing
`m4_esyscmd_s([./tools/version.sh])` with `1.0` in the call to
`AC_INIT`, then run `autoreconf -i`, etc.

**Comment by manaslkht** [comment]
Hello,

Thank you for your quick reply and the fix. I implemented the changes and the installation worked this time without any errors. 

Thank you!
