### ISSUE TITLE
Associated Atomic Basin / Attractor Index

### ISSUE THREAD

**Issue by ecbrown** [aoterodelaroza/critic2#38]
Is it possible to extract the associated attractor from a starting POINT x.r y.r z.r?   That is, where the gradient ascent path ends up.

**Comment by ecbrown** [comment]
False alarm, I had a syntax error in my FLUXPRINT statement.  Sorry for the noise!

**Comment by aoterodelaroza** [comment]
No worries ;). I was right now writing the answer.
