### ISSUE TITLE
INTEGRALS subscript error

### ISSUE THREAD

**Issue by ecbrown** [aoterodelaroza/critic2#39]
Trying to track down a bug in benzene.wfx, I am trying to perform basin integration on a simple molecule like dihydrogen STO-3G.  My input files:
[h2.cri.txt](https://github.com/aoterodelaroza/critic2/files/6080156/h2.cri.txt)
[h2.cro.txt](https://github.com/aoterodelaroza/critic2/files/6080157/h2.cro.txt)
[h2.wfn.txt](https://github.com/aoterodelaroza/critic2/files/6080158/h2.wfn.txt)

Although critic2 is able to integrate if I call INTEGRALS .... CP 1 explicitly, I expected that omitting the CP would simply integrate the nuclear attractors in a sequence.  Although I don't know exactly what is going on, it may appear that the routine is trying to print info for the bond critical point as well!  (and not ending so well.)

Although I usually use gfortran, I used ifort's -check bounds -traceback to reveal:  

07:07:18 ecbrown@vader h2 → ~/opt/critic2-intel/bin/critic2 h2.cri h2.cro
forrtl: severe (408): fort: (2): Subscript #1 of the array CPCEL has value 1380402516 which is greater than the upper bound of 3:

Image              PC                Routine            Line        Source
critic2            000000000124581F  Unknown               Unknown  Unknown
critic2            0000000000870C12  integration.proc_        2808  integration@proc.f90
critic2            00000000008516AE  integration_mp_in         629  integration@proc.f90
critic2            00000000004D6B52  bisect_mp_integra        1008  bisect@proc.f90
critic2            00000000010A7C9F  MAIN__                    380  critic2.F90
critic2            0000000000406C22  Unknown               Unknown  Unknown
libc-2.31.so       00007FEBDFE130B3  __libc_start_main     Unknown  Unknown
critic2            0000000000406B2E  Unknown               Unknown  Unknown

Line 2808 of integration.proc.f90 does have:
idx = sy%f(sy%iref)%cpcel(icp)%idx

and I confirmed that cpcel(1) = 1, cpcel(2) = 2, and cpcel(3)= 1380402516

I hope this is enough information to track down this bug!

(In gfortran, the output hangs after the NCP printouts and before BCP's, etc.  These latter print in ifort, but their coordinates are NaN.)

**Comment by aoterodelaroza** [comment]
That's odd. What version of critic2 are you using? This input works for me in the development version. Output:
[h2.cro.new.txt](https://github.com/aoterodelaroza/critic2/files/6082602/h2.cro.new.txt)

**Comment by ecbrown** [comment]
I am on HEAD of master.  I looked at your output, and the coordinates of the BCP are garbled.  I think this is where my runs were crashing out.

**Comment by aoterodelaroza** [comment]
Ooops, I see that. Let me take a look.

**Comment by aoterodelaroza** [comment]
It's fixed now, I think. It was a reporting problem. The extra CP was not calculated but the routine that writes the results thought it was there. New output: 
[h2.cro.new.txt](https://github.com/aoterodelaroza/critic2/files/6083127/h2.cro.new.txt). Can you please pull and try again?

**Comment by ecbrown** [comment]
This works on h2 and now benzene.wfx.   (Also working on my new MacBook Pro M1 with gfortran-mp-dev.  It is looking like an integration-beast that rivals my 8-core i9!)

**Comment by aoterodelaroza** [comment]
Sounds good! :)
