### ISSUE TITLE
Redundant variable in struct_drivers@proc.f90

### ISSUE THREAD

**Issue by ecbrown** [aoterodelaroza/critic2#42]
Probably not worth a PR, but I noted this "bug" which prevented ifort from compiling the code.  It seems that lp is defined as lp(inout) and then just lp.

> diff --git a/src/struct_drivers@proc.f90 b/src/struct_drivers@proc.f90
> index 9b81a86..5ae42d7 100644
> --- a/src/struct_drivers@proc.f90
> +++ b/src/struct_drivers@proc.f90
> @@ -2914,7 +2914,7 @@ contains
>      type(crystalseed) :: seed
>      character*1024 :: fname(2)
>      character(len=:), allocatable :: word, lword, wfile, msg
> -    integer :: i, n, is, ns, lp, nat
> +    integer :: i, n, is, ns, nat
>      real*8 :: rms1, rms2, q1(3,3), q2(3,3), xcm1(3), xcm2(3), xnew(3)
>      integer, allocatable :: isuse(:), isperm(:,:)
>      integer, allocatable :: cidxorig(:,:)

**Comment by aoterodelaroza** [comment]
Just pushed the fix. Thanks!

**Comment by ecbrown** [comment]
Worked like a charm, thanks.
