### ISSUE TITLE
Stress tensor pointprop not in json output

### ISSUE THREAD

**Issue by wutobias** [aoterodelaroza/critic2#46]
Hi,

currently as far as I can see the stress tensor is not written to the json output of the `auto` method. Something like

```
molecule molecule.fchk
load molecule.fchk id wfn

reference wfn
POINTPROP stress

auto
CPREPORT verylong
CPREPORT molecule.json verylong
```

will print the stress tensor to stdout but not to the json output. Would it be possible to implement stress tensor in json output? Let me know if you need more specifics.

Regards,
Tobias

**Comment by aoterodelaroza** [comment]
Fixed in the json branch, see #45 . Moving to the other thread.
