### ISSUE TITLE
Load crystal or molecule from file

### ISSUE THREAD

**Issue by davidwaroquiers** [aoterodelaroza/critic2#48]
Hello,

I am struggling to find a way to load a crystal or molecule from a cube file which does not end with .cube, but with .cub. Of course, the easy way is just to rename the file. I am just wondering if there is an equivalent of "LOAD CUBE ANYFILENAME" for the CRYSTAL/MOLECULE keywords.

Not a huge problem but sometimes just a little bit annoying because some software output the cube file as a .cub and if you can just avoid renaming it, that saves you a tiny bit of time ;-)

Thanks a lot.

**Comment by aoterodelaroza** [comment]
Hi David: that's a very good idea - I often have the same problem. It
may take a while because I'm busy with other stuff but I'll try to put
it in soon.

**Comment by davidwaroquiers** [comment]
Thanks for your quick answer and thanks a lot for this nice package ;-)

**Comment by aoterodelaroza** [comment]
Hi David: I've just implemented this change - sorry for the wait. See:
https://aoterodelaroza.github.io/critic2/manual/crystal/#files-with-other-extensions
and
https://aoterodelaroza.github.io/critic2/manual/molecule/#files-with-other-extensions .
If you have some time, could you please give it a spin with one of
your cub files? Thanks!

**Comment by aoterodelaroza** [comment]
I'll tentatively close this issue. Feel free to reopen.

**Comment by davidwaroquiers** [comment]
Dear Alberto,


Sorry for not answering your message earlier. Thanks for implementing this! I will give it a try and let you know!


Best,


David
