### ISSUE TITLE
Error using Make

### ISSUE THREAD

**Issue by pies32** [aoterodelaroza/critic2#49]
Hi there, 

I am trying to compile and use critic2-stable on a Linux machine and am running into this error. My process is installing from GitHub, going to the directory and typing in autoreconf, ./configure, followed by make. This issue arises when I run make. Here is the entire error.

hashtype.f90:26.41:

     character(len=:), allocatable :: key
                                         1
Error: Deferred-length character component 'key' at (1) is not yet supported
hashtype.f90:26.41:

     character(len=:), allocatable :: key
                                         1
Error: Deferred-length character component 'key' at (1) is not yet supported
hashtype.f90:26.41:

     character(len=:), allocatable :: key
                                         1
Error: Deferred-length character component 'key' at (1) is not yet supported
hashtype.f90:413.40:

             call self%assign(self%next)
                                        1
Error: 'assign' at (1) should be a SUBROUTINE
hashtype.f90:26.41:

     character(len=:), allocatable :: key
                                         1
Error: Deferred-length character component 'key' at (1) is not yet supported
hashtype.f90:296.54:

    call self%root(hashfun(key,self%len))%put(key,val)
                                                      1
Error: 'put' at (1) should be a SUBROUTINE
hashtype.f90:276.54:

    call self%root(hashfun(key,self%len))%put(key,val)
                                                      1
Error: 'put' at (1) should be a SUBROUTINE
hashtype.f90:256.54:

    call self%root(hashfun(key,self%len))%put(key,val)
                                                      1
Error: 'put' at (1) should be a SUBROUTINE
hashtype.f90:236.54:

    call self%root(hashfun(key,self%len))%put(key,val)
                                                      1
Error: 'put' at (1) should be a SUBROUTINE
hashtype.f90:216.12:

    iskey = self%root(fh)%iskey(key)
            1
Error: 'iskey' at (1) should be a FUNCTION
hashtype.f90:200.36:

    call self%root(fh)%get(key,oval)
                                    1
Error: 'get' at (1) should be a SUBROUTINE
hashtype.f90:184.35:

    call self%root(fh)%get(key,str)
                                   1
Error: 'get' at (1) should be a SUBROUTINE
hashtype.f90:166.35:

    call self%root(fh)%get(key,str)
                                   1
Error: 'get' at (1) should be a SUBROUTINE
hashtype.f90:149.35:

    call self%root(fh)%get(key,str)
                                   1
Error: 'get' at (1) should be a SUBROUTINE
hashtype.f90:132.35:

    call self%root(fh)%get(key,str)
                                   1
Error: 'get' at (1) should be a SUBROUTINE
hashtype.f90:113.31:

       call self%root(i)%free()
                               1
Error: 'free' at (1) should be a SUBROUTINE
hashtype.f90:26.41:

     character(len=:), allocatable :: key
                                         1
Error: Deferred-length character component 'key' at (1) is not yet supported
make[2]: *** [hashtype.o] Error 1
make[2]: Leaving directory `/home/USER/critic2-stable/src'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/home/USER/critic2-stable/src'
make: *** [all-recursive] Error 1

I am following the manual for installation exactly as it is written. Do you have any suggestions or things I can try to fix this? What information do you need from me?

Thank you.

**Comment by aoterodelaroza** [comment]
Hi Travis: you are probably using an old version of gfortran, or some
other compiler that is not up to date with the Fortran standard. See: 
https://aoterodelaroza.github.io/critic2/installation/#whichcompilerswork
Which compiler & version are you using?

**Comment by pies32** [comment]
> Hi Travis: you are probably using an old version of gfortran, or some other compiler that is not up to date with the Fortran standard. See: https://aoterodelaroza.github.io/critic2/installation/#whichcompilerswork Which compiler & version are you using?

GNU Fortran (GCC) 4.8.5 20150623 (Red Hat 4.8.5-39)

I see this is not supported. Thank you for the help. I'm not able to update this since it is a lab workstation.  Do you have any recommendations?

**Comment by aoterodelaroza** [comment]
You can download and install the Intel fortran compiler. As far as I
know, it is free of charge and you can install it on your own
account.

**Comment by pies32** [comment]
> You can download and install the Intel fortran compiler. As far as I know, it is free of charge and you can install it on your own account.

I will give it a shot, thank you!
