### ISSUE TITLE
Error in `critic2': munmap_chunk(): invalid pointer

### ISSUE THREAD

**Issue by const-sctms** [aoterodelaroza/critic2#5]
Dear friends,
critic2 configured with 
./configure FC=ifort CC=icc CXX=icpc FCFLAGS="-O2 -no-ip" CFLAGS="-O2 -no-ip" CXXFLAGS="-O2 -no-ip" --with-libxc-prefix=/usr/local/libxc3.0.0 --with-libxc-include=/usr/local/libxc3.0.0/include
and compiled with Intel Composer XE 2015 (patch 2) was abnormally terminating with

*** Error in `critic2': munmap_chunk(): invalid pointer: 0x00002b72fbffea90 ***

"export OMP_STACKSIZE=128M" (or 256M or 512M) doesn't any positive effect, address
of invalid pointer was changed only.

critic2 configured and built without MP (with the same options above but "--disable-openmp") works fine in the same task on the same host and OS ($ uname -srm  Linux 3.13.0-39-generic x86_64
CPU Intel Xeon CPU E5-2650 2GHz).
You can see in configure options that I use own build of libxc but it was optimized for AVX instruction set only, hasn't any special option for OpenMP at configure time and linked in working non-MP build too.
I think that task's input files are needed but size of archive (200+ MB) is too big for this site :( So I can send it by e-mail or place on web-server for You to download.

With respect and best wishes

**Comment by aoterodelaroza** [comment]
Hi @const-sctms,

It could be a bug in critic2, or it could be something going on with
the compiler - I've had problems in the past with memory allocation
and openmp blocks in ifort. If you could please send me the input
files, as you suggest, I'll take a look. In the meantime, you may want
to try deactivating the optimization flag (say, use -O1 or -O0).

Cheers!

* const-sctms <notifications@github.com> [2017-06-05 07:38:46 -0700]:

**Comment by const-sctms** [comment]
Ok, I've built critic2 after "./configure FC=ifort CC=icc CXX=icpc FCFLAGS="-O0" CFLAGS="-O0" CXXFLAGS="-O0" --with-libxc-prefix=/usr/local/libxc3.0.0 --with-libxc-include=/usr/local/libxc3.0.0/include" and run the same task again. In this case computations were finished without error message but too early - after 143 line of "Critical points list" (in success calculations this list were ended at 141 line and followed with "Analysis of system bonds" etc up to "CRITIC2 ended succesfully (0 WARNINGS, 0 COMMENTS)" and CPU timings).
Task's input files are attached except CHGCAR (700MB)
[infiles.zip](https://github.com/aoterodelaroza/critic2/files/1052420/infiles.zip)

**Comment by aoterodelaroza** [comment]
I think I can reproduce the error with ifort 14.0.2.144 and a made-up density for this system. It gives me a "bus error" right after the critical point list. Adding the -C option to FCFLAGS (activate all compiler checks) and keeping -O0 seems to work for me. I'm still looking for a better solution, though.

**Comment by aoterodelaroza** [comment]
It seems like a regression in the compiler - those flags you used seem to work with ifort 12.1.5.399 and 12.1.0. If you have access to a different (earlier?) version of ifort, you may want to try that, too.

**Comment by aoterodelaroza** [comment]
I've just pushed a fix for this. The problem is related to the fact that the openmp specs do not contemplate how to deal with user-defined types with allocatable components (as in the scalar_value type from types.f90). I've solved this by wrapping the grd call in an internal function, therefore making scalar_value automatic upon entry. Could you please pull and let me know if it works?

**Comment by const-sctms** [comment]
OK, I've downloaded new code and built with Intel compiler v12.1.6 begining with "-O0" and with "-O2 -xAVX" at the end. Both executable works fine and with optimized one using up to 8 core I've got following timings:
"CRITIC2 ended succesfully (0 WARNINGS, 0 COMMENTS)
Elapsed wall time: 22s
Elapsed CPU time: 32s"
They are better than with "--disable-openmp". 
Additionally I'm going to compile new code with Intel compiler v14 and v15 for accurate check.
Many thanks and best wishes!

**Comment by aoterodelaroza** [comment]
Thanks for the report, and I'm glad it's solved. I think the last fix should make critic2 work with any ifort/icc, even the 14.x and 15.x series.

**Comment by const-sctms** [comment]
I've checked with ifort/icc 15.0.2 and additionally with "-static-intel" linking option. 
It works and some faster then previous (on the same 8 cores):
CRITIC2 ended succesfully (0 WARNINGS, 0 COMMENTS)
Elapsed wall time: 20s
Elapsed CPU time: 27s
