### ISSUE TITLE
Missing manual PDF

### ISSUE THREAD

**Issue by arosen93** [aoterodelaroza/critic2#51]
In the PDF made available in the .tar.gz archive of critic2 in the original critic2 paper, there is a `doc/user-guide.pdf` that is quite helpful. However, on this github repo, there is no longer a `doc` folder, and I can't find the `user-guide.pdf`. I'm not sure if this is intentional or not, but I wanted to let you know. Feel free to close as you see fit.

**Comment by aoterodelaroza** [comment]
Sorry, I moved over to the [online documentation](https://aoterodelaroza.github.io/critic2/) quite a few years ago, and the PDF no longer exists. The website is more or less in the same order as the PDF manual from long ago and the search functionality is quite useful. If it helps, you can perhaps make a PDF from the markdown documents in the [website repo](https://github.com/aoterodelaroza/aoterodelaroza.github.io/tree/master/_critic2), although I understand this is not ideal.

**Comment by arosen93** [comment]
Thanks, that makes total sense. Just wanted to make sure I wasn't missing something. Website seems perfect!
