### ISSUE TITLE
VMD visualization fails

### ISSUE THREAD

**Issue by cisert** [aoterodelaroza/critic2#56]
Following [this page in the manual](https://aoterodelaroza.github.io/critic2/manual/cpsearch/#c2-cpreport), I'm trying to write a VMD session file using the CPREPORT keyword (see [input.cri.txt](https://github.com/aoterodelaroza/critic2/files/10556567/input.cri.txt); all files have `.txt` suffix so Github lets me upload them). This is based on a DFTB+ calculation. 

I get the error message (see also [complete output](https://github.com/aoterodelaroza/critic2/files/10556568/output.cri.txt))

```
%% cpreport water.vmd graph

!error!  water.vmd
ERROR(struct_write): unrecognized file format
```

If I run the same script but with `cpreport water.cml graph`, the program completes successfully. I believe I'm using the core density augmentation correctly (`zpsp c 2` in [input.cri.txt](https://github.com/aoterodelaroza/critic2/files/10556567/input.cri.txt) for 6 non-core electrons in oxygen), though I'm not 100% sure and perhaps this contributes to the issue? 

Any help on how to successfully write a VMD session file would be greatly appreciated! 

Thanks and best, 
Clemens

Additional files for reproducing the calculation: 
[detailed.xml.txt](https://github.com/aoterodelaroza/critic2/files/10556049/detailed.xml.txt) (output from DFTB+ calculation)
[geom.out.gen.txt](https://github.com/aoterodelaroza/critic2/files/10556050/geom.out.gen.txt) (molecule geometry)

**Comment by aoterodelaroza** [comment]
Hi Clemens: sorry for the wait. The vmd output of CPREPORT is working
for me with a very similar input. Are you sure you are using the
latest version from the master branch of the repo? This is a
relatively new feature and the packaged versions likely don't have it
(and the stable version certainly doesn't have it).

**Comment by cisert** [comment]
Thanks for the answer! I was using the stable version, so that clears it up.
