### ISSUE TITLE
critic2 : cp error for smoothrho

### ISSUE THREAD

**Issue by zanat** [aoterodelaroza/critic2#58]
%% load rhoae.cube smoothrho

!error! smoothrho
ERROR(setfield): Unknown extra keyword
ERROR(setfield): Unknown extra keyword
1

**Comment by aoterodelaroza** [comment]
Works for me. Are you sure you are using the latest version from the repo?

**Comment by zanat** [comment]
I tried both versions: Version 1.1:  critic2-1.1dev.zip  and 1.1stable.tar.gz 
from: https://aoterodelaroza.github.io/critic2/

**Comment by zanat** [comment]
it works using latest version in gihub repo.
