### ISSUE TITLE
error reading STO molden files

### ISSUE THREAD

**Issue by masterofamn2** [aoterodelaroza/critic2#60]
Hi,

I just want to report a small bug(?) in the current GIT version of critic2: 

When trying to load a molden STO-type file, critic2 always stops with error `Error reading file` because in line 1869 of `wfn_private@proc.F90` the `errmsg` is once set per default as it seems to the above message but never re-set to "" before returning to the call from` fieldmod@proc` in line 2282. 

(This  happened when using a molden file generated from an ADF wave function.)

**Comment by aoterodelaroza** [comment]
Hi @masterofamn2 : it's possible something has changed in the ADF generation routines or last time I coded it I didn't consider all the format options for the file. MOLDEN-style files have n different and incompatible formats, unfortunately. Would you be able to send me the file so I can take a look?

**Comment by masterofamn2** [comment]
Yes, shure - I'll send the file via mail.

**Comment by aoterodelaroza** [comment]
Ah, sorry, I got it a few days ago but it went right into the SPAM folder for some reason. I'll take a look in the next few days.

**Comment by aoterodelaroza** [comment]
The problem was a bug: the STO file was correctly read but the reading routine returned with a non-zero error message after I changed the error message handling facilities for the GUI. I've just pushed the fix to the repo and it should be solved now:
```
molecule test.molden
load test.molden
meshtype becke good
molcalc
```
gives:
```
+ Field integral = 12.00000430   
```
Can you please git pull and check?
