### ISSUE TITLE
Unable to install critic2

### ISSUE THREAD

**Issue by kpmp6** [aoterodelaroza/critic2#61]
I tried to install critic2 but I couldn't able to install it and I am new to Linux. can you please upload a video for installation?

**Comment by aoterodelaroza** [comment]
Sorry, I don't do videos. The installation instructions are here: https://aoterodelaroza.github.io/critic2/installation/ . If you need help with Linux, the easiest is probably to contact someone at your institution who knows or look up online tutorials.
