### ISSUE TITLE
Negative values for the reduced density gradient

### ISSUE THREAD

**Issue by pth-lab** [aoterodelaroza/critic2#64]
I used Critic2 to calculate the NCI plot for the case of organic compound adsorbed on the metal surface, but the results obtained had some very large negative values ​​of RDG when density reached zero. I want to know why and is there any way to fix it, thanks.

**Comment by aoterodelaroza** [comment]
The RDG should not be negative. It is possible this is an artifact of
the grid interpolation method you chose, but it is difficult to say
without more information.

**Comment by pth-lab** [comment]
Thank you for your reply. I tried changing the grid interpolation method, and it gave more reasonable results. Thanks again.
