### ISSUE TITLE
Add support for FPLO

### ISSUE THREAD

**Issue by mretegan** [aoterodelaroza/critic2#69]
It would be useful (at least for one person 😄) to have support for reading data from FPLO (https://www.fplo.de). The program supports saving data as OpenDX files but not Cube.

**Comment by aoterodelaroza** [comment]
OpenDX does not seem too terrible to implement :D (though it may take
me a while). I don't have an FPLO licence. Would you mind sending over
an example OpenDX file to use it as reference?

**Comment by mretegan** [comment]
The [fplo_data.tar.gz](https://github.com/aoterodelaroza/critic2/files/15106828/fplo_data.tar.gz) archive contains complete FPLO calculations on quartz and covellite. I also exported the density in an openDX file for both. Please let me know if you need additional files.

**Comment by aoterodelaroza** [comment]
I think the easiest would be to read the `grid_dens.001` file (is
`001` always the extension of this file?). However, this file doesn't
contain the atomic positions, and I need to get that info from
somewhere else for the structure to be consistent with the
density. What is the input file for the run? Is `scf.out` the output
and `.out` the default extension for it? If so, I could probably read
the structural info from there.

**Comment by mretegan** [comment]
The input file for the FPLO calculation is `=.in`, and the name is fixed. You can extract structural information from it.
The name of the output file is not standard. The suffix `.001` in the `grid_dens` file labels the first and only grid data I right-out for this calculation (see screenshot below).

![Screenshot 2024-04-29 at 09 44 23](https://github.com/aoterodelaroza/critic2/assets/93124/dfc7ef0f-ce92-4c1a-972c-8b4fb2c32848)

**Comment by yquana** [comment]
> OpenDX does not seem too terrible to implement :D (though it may take me a while). I don't have an FPLO licence. Would you mind sending over an example OpenDX file to use it as reference?

FPLO is free for academic use, I think.

**Comment by aoterodelaroza** [comment]
Reading FPLO outputs and grids is implemented. The input files are just too weird to parse, so this was the best option. You can now do:
```
crystal scf.out
load grid_dens.001
```
The first command reads the crystal structure from the output and the second reads the grid. The extensions "understood" by critic2 are "out" for the output and "001" for the grid but, as usual, you can force a particular format:
```
crystal fplo blah
load fplo bleh
```
I have made some assumptions re what the contents of both files are, so be aware that it may break down if conditions change. For the two examples you sent, it seems to be working, though. Would you please try it and let me know?
