### ISSUE TITLE
Unknown extra keyword error

### ISSUE THREAD

**Issue by Vahid999** [aoterodelaroza/critic2#70]
Hello,

Using the QE example with NC pseudo-potentials, my input file is

crystal rho.cube
load rho.cube core zpsp Mo 14 S 6 Bi 23 C 4
load rho.cube
integrable 2
yt

The numbers in line 2 are z_valence values from the NC PSP.

The output shows the following error

%% load rho.cube core zpsp Mo 14 S 6 Bi 23 C 4
ERROR : load rho.cube core zpsp Mo 14 S 6 Bi 23 C 4
ERROR (load): unknown extra keyword

I would appreciate any hints as to the source of these errors.

Thanks,
Vahid

**Comment by aoterodelaroza** [comment]
Sorry for the wait. I changed the syntax for ZPSP recently but forgot
to update the examples. I'm in the process of doing that now. It'll
work if you simply remove the "core" keyword.

**Comment by Vahid999** [comment]
Great. Many thanks.
Vahid

On May 11, 2024, at 11:49 AM, aoterodelaroza ***@***.***> wrote:

CAUTION: The Sender of this email is not from within Dalhousie.

Sorry for the wait. I changed the syntax for ZPSP recently but forgot
to update the examples. I'm in the process of doing that now. It'll
work if you simply remove the "core" keyword.
