### ISSUE TITLE
Core Dump Error in running examples 

### ISSUE THREAD

**Issue by rezabma** [aoterodelaroza/critic2#9]
I have compiled critic 2 by gfortran 5.4 on ubuntu16.04 LTS.I used autoreconf -i,  ./configure,   make.
I get following error:
==================================================
reza@Astek:~/critic2-master/examples/visualization_cps$ /home/reza/critic2-master/src/critic2 <hf6.cri 

Program received signal SIGSEGV: Segmentation fault - invalid memory reference.

Backtrace for this error:
#0  0x2AE739A32E08
#1  0x2AE739A31F90
#2  0x2AE73A2964AF
#3  0x589334 in __systemmod_MOD_systemmod_init at systemmod.f90:101 (discriminator 434)
#4  0x41AD13 in MAIN__ at critic2.F90:80 (discriminator 9)
Segmentation fault (core dumped)
Any help?

**Comment by aoterodelaroza** [comment]
Either use gfortran 6.x or newer or download and compile the stable version. See:
https://github.com/aoterodelaroza/critic2#which-compilers-work

**Comment by rezabma** [comment]
Thanks. I could ran examples with your comment. I used gfortran-7.
However, I have a problem for making src-gui. With make command, I found following error:
==========================================
reza@Astek:~/critic2-master/src-gui$ make
Making all in imgui
make[1]: Entering directory '/home/reza/critic2-master/src-gui/imgui'
true imgui.o imgui_draw.o imgui_impl_glfw_gl3.o imgui_demo.o imgui_dock.o imgui_widgets.o gl3w.o  
make[1]: Leaving directory '/home/reza/critic2-master/src-gui/imgui'
Making all in .
make[1]: Entering directory '/home/reza/critic2-master/src-gui'
g++ -DPACKAGE_NAME=\"critic2\" -DPACKAGE_TARNAME=\"critic2\" -DPACKAGE_VERSION=\"no-git\" -DPACKAGE_STRING=\"critic2\ no-git\" -DPACKAGE_BUGREPORT=\"aoterodelaroza@gmail.com\" -DPACKAGE_URL=\"\" -DPACKAGE=\"critic2\" -DVERSION=\"no-git\" -I.    -I../include `pkg-config --cflags glfw3` -Wall -Wformat -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++11 -w -g -g -O2 -MT main.o -MD -MP -MF .deps/main.Tpo -c -o main.o main.cpp
main.cpp: In function ‘int main(int, char**)’:
main.cpp:104:45: error: ‘GLFW_TRUE’ was not declared in this scope
           glfwSetWindowShouldClose(rootwin, GLFW_TRUE);
                                             ^~~~~~~~~
Makefile:437: recipe for target 'main.o' failed
make[1]: *** [main.o] Error 1
make[1]: Leaving directory '/home/reza/critic2-master/src-gui'
Makefile:457: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1

**Comment by aoterodelaroza** [comment]
The GUI is not ready yet, sorry.

**Comment by rezabma** [comment]
Thank you anyway. I will use critic2 in my research, and ask you if there is any question. Thank you again.

**Comment by aoterodelaroza** [comment]
No worries. It will still take me a while to get going with the GUI. In the meantime, I suggest using avogadro and the other GUIs indicated in the manual.
